services:
    api-gateway:
        build: ./backend/services/api-gateway
        image: api-gateway:1.0
        env_file:
            - ./backend/services/api-gateway/.env
        ports:
            - "3000:3000"
        depends_on:
            - auth-service
            - sucursal-service
            - turno-service
        networks:
            - turnos-network

    auth-service:
        build: ./backend/services/auth-service
        image: auth-service:1.0
        env_file:
            - ./backend/services/auth-service/.env
        ports:
            - "3001:3000"
        networks:
            - turnos-network

    sucursal-service:
        build: ./backend/services/sucursal-service
        image: sucursal-service:1.0
        env_file:
            - ./backend/services/sucursal-service/.env
        ports:
            - "3002:3000"
        networks:
            - turnos-network

    turno-service:
        build: ./backend/services/turno-service
        image: turno-service:1.0
        env_file:
            - ./backend/services/turno-service/.env
        ports:
            - "3003:3000"
        networks:
            - turnos-network

networks:
    turnos-network:
        driver: bridge
