services:
    # --- 1 FRONTEND ---
    frontend:
        image: nginx:alpine
        container_name: restaurante-app
        ports:
            - "8080:80" # Los usuarios entran por el puerto 8080
        volumes:
            - ./frontend:/usr/share/nginx/html
        networks:
            - red-restaurante

    # --- 2 API GATEWAY ---
    api-gateway:
        image: nginx:alpine
        container_name: api-gateway
        ports:
            - "3000:80" # El Frontend enviará sus peticiones de datos aquí
        networks:
            - red-restaurante
        depends_on:
            - ms-usuarios
            - ms-pedidos
            - ms-catalogo

    # --- 3. MICROSERVICIO DE USUARIOS ---
    ms-usuarios:
        build: ./servicios/usuarios
        container_name: ms-usuarios
        networks:
            - red-restaurante

    # --- 4. MICROSERVICIO DE PEDIDOS ---
    ms-pedidos:
        build: ./servicios/pedidos
        container_name: ms-pedidos
        networks:
            - red-restaurante

    # --- 5. MICROSERVICIO DE CATALOGO ---
    ms-catalogo:
        build: ./services/catalogo
        container_name: ms-catalogo
        networks:
            - red-restaurante

    # --- 6. BASE DE DATOS ---
    db:
        image: mongo:latest
        container_name: mongodb-datos
        networks:
            - red-restaurante

networks:
    red-restaurante:
        driver: bridge
